[env:drive_esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_microros_distro = jazzy
board_microros_transport = serial
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB0
build_src_filter = +<movementwithpid_node.cpp>
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    adafruit/Adafruit BNO055
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor
    madhephaestus/ESP32Encoder

[env:sys_esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_microros_distro = jazzy
board_microros_transport = serial
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/ttyUSB0
build_src_filter = +<planting_node.cpp>
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    adafruit/Adafruit BNO055
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor
    madhephaestus/ESP32Servo
    adafruit/Adafruit INA219